import type { Item } from './types';

export const mockItems: Item[] = [
  {
    id: '4-resume',
    type: 'pdf',
    title: '周国梁 - 车辆工程专业本科.pdf',
    fileSize: '0.4 MB',
    pageCount: 1,
    thumbnail: '/images/zhou_resume_preview.png',
    content: '周国梁的个人简历。成都大学车辆工程 2026 届本科，具备 Python、AI 工程、LLM Agent、RAG 知识库和全栈开发经验。',
    summary: '成都大学车辆工程 2026 届本科生，具备 Python、AI 工程、LLM Agent 系统和 RAG 知识库经验。',
    keyClaims: [
      '熟悉 Python、React/TypeScript 和 AI 工程开发。',
      '具备 LLM Agent、RAG 知识库与工作流编排经验。',
      '有研究助理、质量测试和全栈项目经验。',
    ],
    whyItMatters: 'Represents personal PDF archive usage inside Lovcore.',
    tags: ['Document', 'Prompt Engineering', 'LLM Agent', 'AI工程'],
    status: 'ready',
    createdAt: '2026-05-22T07:10:00Z',
  },
  {
    id: '9',
    type: 'video',
    title: 'NVIDIA GTC 2026 Keynote',
    sourceUrl: 'https://www.nvidia.com/gtc/keynote/',
    duration: '120:00',
    thumbnail: '/images/computation_node.png',
    content: 'NVIDIA roadmap for Blackwell chips, physical AI agent systems, and sovereign computing clouds.',
    summary: 'NVIDIA developer keynote outlining Blackwell deployments, robotics training, and datacenter grids.',
    keyClaims: [
      'Data centers are transitioning to generative AI factories.',
      'Physical AI represents the next frontier of model application.',
      'Hardware scaling continues through multi-node GPU clustering.',
    ],
    whyItMatters: 'Core infrastructure roadmap reference.',
    tags: ['nvidia', 'infrastructure', 'keynote', 'hardware', 'gpu'],
    status: 'ready',
    createdAt: '2026-05-21T10:15:00Z',
  },
  {
    id: '2-saas-note',
    type: 'note',
    title: 'AI Labor Thesis',
    content: 'Traditional SaaS charges a subscription fee per employee seat, assuming human productivity is the value unit. When an AI agent performs 100% of the task (e.g. drafting customer support, resolving code, filing records), c...',
    summary: 'A founder note about AI-native companies selling completed work instead of software seats.',
    keyClaims: [
      'Seat pricing breaks when agents complete the work.',
      'AI-native products should price around outcomes.',
    ],
    whyItMatters: 'Keeps the business thesis visible as a quiet memo card.',
    tags: ['ai', 'services', 'software', 'sequoia', 'business-model'],
    noteBgColor: 'rgba(230, 226, 218, 0.65)',
    status: 'ready',
    createdAt: '2026-05-22T08:30:00Z',
  },
  {
    id: '1',
    type: 'video',
    title: 'This is AGI: Sequoia AI Ascent 2026 Keynote',
    sourceUrl: 'https://www.youtube.com/watch?v=LRo33rnv6rQ',
    duration: '22:15',
    thumbnail: '/images/sequoia_agi_screenshot.png',
    content: 'Sequoia Capital keynote on the AGI threshold in 2026. Arguing that long-horizon agents make agentic workflows ready for enterprise builders.',
    summary: 'A Sequoia keynote arguing that long-horizon agents make 2026 a practical AGI threshold for business builders.',
    keyClaims: [
      'Agentic workflows have crossed the threshold of economic viability.',
      'System-2 reasoning at test-time is replacing static model scale.',
      'The value of AI is shifting from software seat-licensing to selling completed services.',
    ],
    whyItMatters: 'Canonical example of saving a business technology video and turning it into searchable thesis cards.',
    tags: ['ai', 'agi', 'agents', 'sequoia', 'keynote', 'business-model'],
    status: 'ready',
    createdAt: '2026-05-22T09:00:00Z',
  },
  {
    id: '5',
    type: 'link',
    title: 'AI + a16z',
    sourceUrl: 'https://a16z.com/ai/',
    thumbnail: '/images/a16z_screenshot.png',
    content: 'Andreessen Horowitz artificial intelligence ecosystem hub: essays, infrastructure stack guides, and developer podcasts.',
    summary: 'A hub of AI essays, open-source projects, podcasts, and market perspectives from a16z.',
    keyClaims: [
      'The AI stack is stabilizing around unified runtime orchestrators.',
      'Context-window expansion changes database architectures.',
      'Sovereign AI clouds are emerging as an infrastructure tier.',
    ],
    whyItMatters: 'Good benchmark for article/link cards and topic filtering.',
    tags: ['ai', 'a16z', 'research', 'venture', 'podcast'],
    status: 'ready',
    createdAt: '2026-05-22T06:40:00Z',
  },
  {
    id: '10',
    type: 'pdf',
    title: '2026 Agentic Coding Trends Report.pdf',
    fileSize: '8.7 MB',
    pageCount: 84,
    thumbnail: '/images/agentic_coding_report_cover.png',
    content: 'Anthropic research paper investigating how software development teams adopt terminal and editor agents.',
    summary: 'Anthropic research on agentic coding, multi-agent workflows, developer orchestration, and organizational adoption.',
    keyClaims: [
      'Developer velocity increases for standard debugging and refactoring tasks.',
      'Code review shifts toward intent validation.',
      'High-context terminal interfaces perform well in complex refactors.',
    ],
    whyItMatters: 'Key research reference supporting Lovcore developer integrations.',
    tags: ['anthropic', 'report', 'agentic-coding', 'software-3', 'research'],
    status: 'ready',
    createdAt: '2026-05-20T16:50:00Z',
  },
  {
    id: '15',
    type: 'link',
    title: 'Conviction AI',
    sourceUrl: 'https://www.conviction.com/',
    thumbnail: '/images/conviction_screenshot.png',
    content: 'Conviction is a venture capital firm founded by Sarah Guo, backing Software 3.0 and AI-native startups.',
    summary: 'Minimalist portfolio landing page of Conviction, an early-stage venture fund focused on Software 3.0.',
    keyClaims: [
      'The stack is rebuilding from the database up around model capability.',
      'AI investments require highly technical, founder-first diligence.',
    ],
    whyItMatters: 'Useful benchmark for visual minimalism and venture portfolio presentation.',
    tags: ['venture', 'conviction', 'software-3', 'portfolio', 'investment'],
    status: 'ready',
    createdAt: '2026-05-18T14:30:00Z',
  },
  {
    id: '2',
    type: 'article',
    title: 'Services: The New Software',
    sourceUrl: 'https://sequoiacap.com/article/services-the-new-software/',
    content: 'The economics of foundation models differ fundamentally from SaaS. Instead of flat hosting costs, model providers face compute expenses that scale directly with the depth of reasoning and value delivered.',
    summary: 'Sequoia thesis that AI-native companies can sell completed work instead of software tools.',
    keyClaims: [
      'The SaaS market expands into the global labor market.',
      'AI allows companies to sell completed work instead of software seats.',
      'Pricing models shift from subscription seats to outcomes.',
    ],
    whyItMatters: 'Useful for defining Lovcore as a place where saved knowledge turns into executable work.',
    tags: ['ai', 'services', 'software', 'sequoia', 'autopilot', 'business-model'],
    noteBgColor: 'rgba(230, 226, 218, 0.65)',
    status: 'ready',
    createdAt: '2026-05-22T08:30:00Z',
  },
  {
    id: '6',
    type: 'note',
    title: 'Lovcore positioning',
    content: 'Lovcore should feel like mymind for AI business intelligence: save anything, organize nothing, search by memory, and later turn saved sources into briefs for agents.',
    summary: 'A positioning note for Lovcore as a private AI/business memory archive.',
    keyClaims: [
      'Focus on frictionless collection of premium tech signals.',
      'Zero cognitive overhead for user categorization.',
      'Bridge between human knowledge intake and agentic execution workflows.',
    ],
    whyItMatters: 'A realistic founder note that should look beautiful as a private thought card.',
    tags: ['lovcore', 'positioning', 'memory', 'private-archive', 'product-thinking'],
    noteBgColor: 'rgba(238, 233, 224, 0.65)',
    status: 'ready',
    createdAt: '2026-05-22T06:10:00Z',
  },
  {
    id: '11',
    type: 'article',
    title: 'OpenAI: A Business That Scales With The Value Of Intelligence',
    sourceUrl: 'https://openai.com/index/a-business-that-scales-with-the-value-of-intelligence/',
    content: 'The economics of foundation models differ fundamentally from SaaS. Model providers face compute expenses that scale with depth of thinking and inference-time reasoning.',
    summary: 'Analysis of economic shifts in AI businesses and the value scaling of intelligence.',
    keyClaims: [
      'Model pricing will evolve to reflect the cognitive value of output.',
      'Inference-time search is becoming the dominant driver of compute demand.',
      'The marginal cost of intelligence continues to fall.',
    ],
    whyItMatters: 'Venture economics model for computing businesses.',
    tags: ['openai', 'economics', 'compute', 'inference', 'business-model'],
    status: 'ready',
    createdAt: '2026-05-20T11:20:00Z',
  },
  {
    id: '17',
    type: 'note',
    title: 'Multi-Agent Swarm Sync Protocol',
    content: 'Technical design scratchpad for swarm memory sync:\n\n1. State sync must be asynchronous and event-driven to avoid blocking execution threads.\n2. Use vector indexes for long-term memory retrieval, and short-term append-only lists for immediate session context.\n3. Implement token pruning heuristics to prevent context bloat during long-horizon tasks.',
    summary: 'Technical notes on multi-agent swarm state synchronization, memory indexing, and token budget management.',
    keyClaims: [
      'Asynchronous state synchronization is mandatory for responsive agent grids.',
      'Token pruning heuristics are key to sustaining context window margins.',
    ],
    whyItMatters: 'Reference note for future multi-agent workspace pipelines.',
    tags: ['multi-agent', 'protocol', 'software-engineering', 'memory-sync', 'notes'],
    noteBgColor: 'rgba(220, 226, 222, 0.65)',
    status: 'ready',
    createdAt: '2026-05-17T16:10:00Z',
  },
  {
    id: '3',
    type: 'link',
    title: 'Claude Code by Anthropic',
    sourceUrl: 'https://www.anthropic.com/product/claude-code',
    thumbnail: '/images/claude_code_screenshot.png',
    content: 'Claude Code is an agentic coding tool that runs in the developer terminal and edits files locally under supervision.',
    summary: 'Anthropic agentic coding product page.',
    keyClaims: [
      'Terminal agent for developers.',
      'Tool usage directly in local environments.',
      'Goal-driven autonomous assistant pattern.',
    ],
    whyItMatters: 'Useful for Lovcore dev-prompt generation and product page analysis.',
    tags: ['anthropic', 'claude-code', 'agentic-coding', 'software-3', 'product'],
    status: 'ready',
    createdAt: '2026-05-22T08:00:00Z',
  },
  {
    id: '4',
    type: 'pdf',
    title: '2026 AI Index Report.pdf',
    fileSize: '14.2 MB',
    pageCount: 482,
    thumbnail: '/images/ai_index_cover.png',
    content: 'Stanford HAI 2026 AI Index Report: foundation models, investment patterns, legislative responses, capability benchmarks, and workforce adoption.',
    summary: 'A macro report on AI progress, industry adoption, investment, policy, and model capabilities.',
    keyClaims: [
      'Global AI venture funding reached record highs.',
      'Frontier models show gains in reasoning APIs.',
      'Enterprise adoption of multi-agent systems increased.',
    ],
    whyItMatters: 'Represents serious PDF/research archive usage.',
    tags: ['stanford', 'ai-index', 'report', 'research', 'policy'],
    status: 'ready',
    createdAt: '2026-05-22T07:15:00Z',
  },
];
